package com.yucong.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.5
 * 2019-02-19T10:25:14.117+08:00
 * Generated source version: 3.2.5
 *
 */
@WebService(targetNamespace = "http://service.yucong.com/", name = "DemoServiceI")
@XmlSeeAlso({ObjectFactory.class})
public interface DemoServiceI {

    @WebMethod
    @RequestWrapper(localName = "sayHello", targetNamespace = "http://service.yucong.com/", className = "com.yucong.service.SayHello")
    @ResponseWrapper(localName = "sayHelloResponse", targetNamespace = "http://service.yucong.com/", className = "com.yucong.service.SayHelloResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String sayHello(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );
}
