package com.yucong.service.imp;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import com.yucong.service.DemoServiceI;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.2.5
 * 2019-02-19T10:25:14.163+08:00
 * Generated source version: 3.2.5
 *
 */
@WebServiceClient(name = "DemoServiceImplService",
                  wsdlLocation = "http://localhost:8080/demo/api?wsdl",
                  targetNamespace = "http://imp.service.yucong.com/")
public class DemoServiceImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://imp.service.yucong.com/", "DemoServiceImplService");
    public final static QName DemoServiceImplPort = new QName("http://imp.service.yucong.com/", "DemoServiceImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/demo/api?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(DemoServiceImplService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "http://localhost:8080/demo/api?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public DemoServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public DemoServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DemoServiceImplService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public DemoServiceImplService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public DemoServiceImplService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public DemoServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns DemoServiceI
     */
    @WebEndpoint(name = "DemoServiceImplPort")
    public DemoServiceI getDemoServiceImplPort() {
        return super.getPort(DemoServiceImplPort, DemoServiceI.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DemoServiceI
     */
    @WebEndpoint(name = "DemoServiceImplPort")
    public DemoServiceI getDemoServiceImplPort(WebServiceFeature... features) {
        return super.getPort(DemoServiceImplPort, DemoServiceI.class, features);
    }

}
